/* soapStub.h
   Generated by gSOAP 2.8.122 for test.h

gSOAP XML Web services tools
Copyright (C) 2000-2021, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#define SOAP_NAMESPACE_OF_ns1	"http://www.example.org/operations/"

#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"
#if GSOAP_VERSION != 208122
# error "GSOAP VERSION 208122 MISMATCH IN GENERATED CODE VERSUS LIBRARY CODE: PLEASE REINSTALL PACKAGE"
#endif


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Structs and Unions                                                         *
 *                                                                            *
\******************************************************************************/

struct _ns1__store_USCOREfile;	/* test.h:169 */
struct _ns1__store_USCOREfileResponse;	/* test.h:185 */
struct _ns1__create_USCOREfile;	/* test.h:201 */
struct _ns1__create_USCOREfileResponse;	/* test.h:217 */
struct _ns1__modify_USCOREfile;	/* test.h:233 */
struct _ns1__modify_USCOREfileResponse;	/* test.h:249 */
struct _ns1__remove_USCOREfile;	/* test.h:265 */
struct _ns1__remove_USCOREfileResponse;	/* test.h:281 */
struct _ns1__store_USCOREexec_USCOREfile;	/* test.h:297 */
struct _ns1__store_USCOREexec_USCOREfileResponse;	/* test.h:313 */
struct _ns1__client_USCORElog_USCOREfiles;	/* test.h:329 */
struct _ns1__NewOperationResponse;	/* test.h:345 */
struct _ns1__client_USCORElog_USCOREfilesResponse1;	/* test.h:361 */
struct __ns1__store_USCOREfile;	/* test.h:494 */

/* test.h:169 */
#ifndef SOAP_TYPE__ns1__store_USCOREfile
#define SOAP_TYPE__ns1__store_USCOREfile (7)
/* complex XML schema type 'ns1:store_file': */
struct _ns1__store_USCOREfile {
        /** Required element 'in' of XML schema type 'xsd:string' */
        char *in;
};
#endif

/* test.h:185 */
#ifndef SOAP_TYPE__ns1__store_USCOREfileResponse
#define SOAP_TYPE__ns1__store_USCOREfileResponse (8)
/* complex XML schema type 'ns1:store_fileResponse': */
struct _ns1__store_USCOREfileResponse {
        /** Required element 'out' of XML schema type 'xsd:string' */
        char *out;
};
#endif

/* test.h:201 */
#ifndef SOAP_TYPE__ns1__create_USCOREfile
#define SOAP_TYPE__ns1__create_USCOREfile (9)
/* complex XML schema type 'ns1:create_file': */
struct _ns1__create_USCOREfile {
        /** Required element 'in' of XML schema type 'xsd:string' */
        char *in;
};
#endif

/* test.h:217 */
#ifndef SOAP_TYPE__ns1__create_USCOREfileResponse
#define SOAP_TYPE__ns1__create_USCOREfileResponse (10)
/* complex XML schema type 'ns1:create_fileResponse': */
struct _ns1__create_USCOREfileResponse {
        /** Required element 'out' of XML schema type 'xsd:string' */
        char *out;
};
#endif

/* test.h:233 */
#ifndef SOAP_TYPE__ns1__modify_USCOREfile
#define SOAP_TYPE__ns1__modify_USCOREfile (11)
/* complex XML schema type 'ns1:modify_file': */
struct _ns1__modify_USCOREfile {
        /** Required element 'in' of XML schema type 'xsd:string' */
        char *in;
};
#endif

/* test.h:249 */
#ifndef SOAP_TYPE__ns1__modify_USCOREfileResponse
#define SOAP_TYPE__ns1__modify_USCOREfileResponse (12)
/* complex XML schema type 'ns1:modify_fileResponse': */
struct _ns1__modify_USCOREfileResponse {
        /** Required element 'out' of XML schema type 'xsd:string' */
        char *out;
};
#endif

/* test.h:265 */
#ifndef SOAP_TYPE__ns1__remove_USCOREfile
#define SOAP_TYPE__ns1__remove_USCOREfile (13)
/* complex XML schema type 'ns1:remove_file': */
struct _ns1__remove_USCOREfile {
        /** Required element 'in' of XML schema type 'xsd:string' */
        char *in;
};
#endif

/* test.h:281 */
#ifndef SOAP_TYPE__ns1__remove_USCOREfileResponse
#define SOAP_TYPE__ns1__remove_USCOREfileResponse (14)
/* complex XML schema type 'ns1:remove_fileResponse': */
struct _ns1__remove_USCOREfileResponse {
        /** Required element 'out' of XML schema type 'xsd:string' */
        char *out;
};
#endif

/* test.h:297 */
#ifndef SOAP_TYPE__ns1__store_USCOREexec_USCOREfile
#define SOAP_TYPE__ns1__store_USCOREexec_USCOREfile (15)
/* complex XML schema type 'ns1:store_exec_file': */
struct _ns1__store_USCOREexec_USCOREfile {
        /** Required element 'in' of XML schema type 'xsd:string' */
        char *in;
};
#endif

/* test.h:313 */
#ifndef SOAP_TYPE__ns1__store_USCOREexec_USCOREfileResponse
#define SOAP_TYPE__ns1__store_USCOREexec_USCOREfileResponse (16)
/* complex XML schema type 'ns1:store_exec_fileResponse': */
struct _ns1__store_USCOREexec_USCOREfileResponse {
        /** Required element 'out' of XML schema type 'xsd:string' */
        char *out;
};
#endif

/* test.h:329 */
#ifndef SOAP_TYPE__ns1__client_USCORElog_USCOREfiles
#define SOAP_TYPE__ns1__client_USCORElog_USCOREfiles (17)
/* complex XML schema type 'ns1:client_log_files': */
struct _ns1__client_USCORElog_USCOREfiles {
        /** Required element 'in' of XML schema type 'xsd:string' */
        char *in;
};
#endif

/* test.h:345 */
#ifndef SOAP_TYPE__ns1__NewOperationResponse
#define SOAP_TYPE__ns1__NewOperationResponse (18)
/* complex XML schema type 'ns1:NewOperationResponse': */
struct _ns1__NewOperationResponse {
        /** Required element 'out' of XML schema type 'xsd:string' */
        char *out;
};
#endif

/* test.h:361 */
#ifndef SOAP_TYPE__ns1__client_USCORElog_USCOREfilesResponse1
#define SOAP_TYPE__ns1__client_USCORElog_USCOREfilesResponse1 (19)
/* complex XML schema type 'ns1:client_log_filesResponse1': */
struct _ns1__client_USCORElog_USCOREfilesResponse1 {
        /** Required element 'out' of XML schema type 'xsd:string' */
        char *out;
};
#endif

/* test.h:494 */
#ifndef SOAP_TYPE___ns1__store_USCOREfile
#define SOAP_TYPE___ns1__store_USCOREfile (23)
/* Wrapper: */
struct __ns1__store_USCOREfile {
        /** Optional element 'ns1:store_file' of XML schema type 'ns1:store_file' */
        struct _ns1__store_USCOREfile *ns1__store_USCOREfile;
};
#endif

/* test.h:750 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (24)
/* SOAP_ENV__Header: */
struct SOAP_ENV__Header {
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* empty struct is a GNU extension */
#endif
};
#endif
#endif

/* test.h:750 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (25)
/* Type SOAP_ENV__Code is a recursive data type, (in)directly referencing itself through its (base or derived class) members */
/* SOAP_ENV__Code: */
struct SOAP_ENV__Code {
        /** Optional element 'SOAP-ENV:Value' of XML schema type 'xsd:QName' */
        char *SOAP_ENV__Value;
        /** Optional element 'SOAP-ENV:Subcode' of XML schema type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Subcode;
};
#endif
#endif

/* test.h:750 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (27)
/* SOAP_ENV__Detail: */
struct SOAP_ENV__Detail {
        char *__any;
        /** Any type of element 'fault' assigned to fault with its SOAP_TYPE_<typename> assigned to __type */
        /** Do not create a cyclic data structure through this member unless SOAP encoding or SOAP_XML_GRAPH are used for id-ref serialization */
        int __type;
        void *fault;
};
#endif
#endif

/* test.h:750 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (30)
/* SOAP_ENV__Reason: */
struct SOAP_ENV__Reason {
        /** Optional element 'SOAP-ENV:Text' of XML schema type 'xsd:string' */
        char *SOAP_ENV__Text;
};
#endif
#endif

/* test.h:750 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (31)
/* SOAP_ENV__Fault: */
struct SOAP_ENV__Fault {
        /** Optional element 'faultcode' of XML schema type 'xsd:QName' */
        char *faultcode;
        /** Optional element 'faultstring' of XML schema type 'xsd:string' */
        char *faultstring;
        /** Optional element 'faultactor' of XML schema type 'xsd:string' */
        char *faultactor;
        /** Optional element 'detail' of XML schema type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *detail;
        /** Optional element 'SOAP-ENV:Code' of XML schema type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Code;
        /** Optional element 'SOAP-ENV:Reason' of XML schema type 'SOAP-ENV:Reason' */
        struct SOAP_ENV__Reason *SOAP_ENV__Reason;
        /** Optional element 'SOAP-ENV:Node' of XML schema type 'xsd:string' */
        char *SOAP_ENV__Node;
        /** Optional element 'SOAP-ENV:Role' of XML schema type 'xsd:string' */
        char *SOAP_ENV__Role;
        /** Optional element 'SOAP-ENV:Detail' of XML schema type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *SOAP_ENV__Detail;
};
#endif
#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/


/* (built-in):0 */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (5)
typedef char *_XML;
#endif

/* (built-in):0 */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (6)
typedef char *_QName;
#endif

/******************************************************************************\
 *                                                                            *
 * Serializable Types                                                         *
 *                                                                            *
\******************************************************************************/


/* char has binding name 'byte' for type 'xsd:byte' */
#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif

/* int has binding name 'int' for type 'xsd:int' */
#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif

/* struct SOAP_ENV__Fault has binding name 'SOAP_ENV__Fault' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (31)
#endif

/* struct SOAP_ENV__Reason has binding name 'SOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (30)
#endif

/* struct SOAP_ENV__Detail has binding name 'SOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (27)
#endif

/* struct SOAP_ENV__Code has binding name 'SOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (25)
#endif

/* struct SOAP_ENV__Header has binding name 'SOAP_ENV__Header' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (24)
#endif

/* struct _ns1__client_USCORElog_USCOREfilesResponse1 has binding name '_ns1__client_USCORElog_USCOREfilesResponse1' for type '' */
#ifndef SOAP_TYPE__ns1__client_USCORElog_USCOREfilesResponse1
#define SOAP_TYPE__ns1__client_USCORElog_USCOREfilesResponse1 (19)
#endif

/* struct _ns1__NewOperationResponse has binding name '_ns1__NewOperationResponse' for type '' */
#ifndef SOAP_TYPE__ns1__NewOperationResponse
#define SOAP_TYPE__ns1__NewOperationResponse (18)
#endif

/* struct _ns1__client_USCORElog_USCOREfiles has binding name '_ns1__client_USCORElog_USCOREfiles' for type '' */
#ifndef SOAP_TYPE__ns1__client_USCORElog_USCOREfiles
#define SOAP_TYPE__ns1__client_USCORElog_USCOREfiles (17)
#endif

/* struct _ns1__store_USCOREexec_USCOREfileResponse has binding name '_ns1__store_USCOREexec_USCOREfileResponse' for type '' */
#ifndef SOAP_TYPE__ns1__store_USCOREexec_USCOREfileResponse
#define SOAP_TYPE__ns1__store_USCOREexec_USCOREfileResponse (16)
#endif

/* struct _ns1__store_USCOREexec_USCOREfile has binding name '_ns1__store_USCOREexec_USCOREfile' for type '' */
#ifndef SOAP_TYPE__ns1__store_USCOREexec_USCOREfile
#define SOAP_TYPE__ns1__store_USCOREexec_USCOREfile (15)
#endif

/* struct _ns1__remove_USCOREfileResponse has binding name '_ns1__remove_USCOREfileResponse' for type '' */
#ifndef SOAP_TYPE__ns1__remove_USCOREfileResponse
#define SOAP_TYPE__ns1__remove_USCOREfileResponse (14)
#endif

/* struct _ns1__remove_USCOREfile has binding name '_ns1__remove_USCOREfile' for type '' */
#ifndef SOAP_TYPE__ns1__remove_USCOREfile
#define SOAP_TYPE__ns1__remove_USCOREfile (13)
#endif

/* struct _ns1__modify_USCOREfileResponse has binding name '_ns1__modify_USCOREfileResponse' for type '' */
#ifndef SOAP_TYPE__ns1__modify_USCOREfileResponse
#define SOAP_TYPE__ns1__modify_USCOREfileResponse (12)
#endif

/* struct _ns1__modify_USCOREfile has binding name '_ns1__modify_USCOREfile' for type '' */
#ifndef SOAP_TYPE__ns1__modify_USCOREfile
#define SOAP_TYPE__ns1__modify_USCOREfile (11)
#endif

/* struct _ns1__create_USCOREfileResponse has binding name '_ns1__create_USCOREfileResponse' for type '' */
#ifndef SOAP_TYPE__ns1__create_USCOREfileResponse
#define SOAP_TYPE__ns1__create_USCOREfileResponse (10)
#endif

/* struct _ns1__create_USCOREfile has binding name '_ns1__create_USCOREfile' for type '' */
#ifndef SOAP_TYPE__ns1__create_USCOREfile
#define SOAP_TYPE__ns1__create_USCOREfile (9)
#endif

/* struct _ns1__store_USCOREfileResponse has binding name '_ns1__store_USCOREfileResponse' for type '' */
#ifndef SOAP_TYPE__ns1__store_USCOREfileResponse
#define SOAP_TYPE__ns1__store_USCOREfileResponse (8)
#endif

/* struct _ns1__store_USCOREfile has binding name '_ns1__store_USCOREfile' for type '' */
#ifndef SOAP_TYPE__ns1__store_USCOREfile
#define SOAP_TYPE__ns1__store_USCOREfile (7)
#endif

/* struct SOAP_ENV__Reason * has binding name 'PointerToSOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (33)
#endif

/* struct SOAP_ENV__Detail * has binding name 'PointerToSOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (32)
#endif

/* struct SOAP_ENV__Code * has binding name 'PointerToSOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (26)
#endif

/* struct _ns1__store_USCOREfileResponse * has binding name 'PointerTo_ns1__store_USCOREfileResponse' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns1__store_USCOREfileResponse
#define SOAP_TYPE_PointerTo_ns1__store_USCOREfileResponse (21)
#endif

/* struct _ns1__store_USCOREfile * has binding name 'PointerTo_ns1__store_USCOREfile' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns1__store_USCOREfile
#define SOAP_TYPE_PointerTo_ns1__store_USCOREfile (20)
#endif

/* _QName has binding name '_QName' for type 'xsd:QName' */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (6)
#endif

/* _XML has binding name '_XML' for type '' */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (5)
#endif

/* char * has binding name 'string' for type 'xsd:string' */
#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif

/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stub Functions                                            *
 *                                                                            *
\******************************************************************************/

    
    /** Web service synchronous operation 'soap_call___ns1__store_USCOREfile' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__store_USCOREfile(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__store_USCOREfile *ns1__store_USCOREfile, struct _ns1__store_USCOREfileResponse *ns1__store_USCOREfileResponse);
    /** Web service asynchronous operation 'soap_send___ns1__store_USCOREfile' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send___ns1__store_USCOREfile(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__store_USCOREfile *ns1__store_USCOREfile);
    /** Web service asynchronous operation 'soap_recv___ns1__store_USCOREfile' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv___ns1__store_USCOREfile(struct soap *soap, struct _ns1__store_USCOREfileResponse *ns1__store_USCOREfileResponse);

/******************************************************************************\
 *                                                                            *
 * Server-Side Operations                                                     *
 *                                                                            *
\******************************************************************************/

    /** Web service operation '__ns1__store_USCOREfile' implementation, should return SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 __ns1__store_USCOREfile(struct soap*, struct _ns1__store_USCOREfile *ns1__store_USCOREfile, struct _ns1__store_USCOREfileResponse *ns1__store_USCOREfileResponse);

/******************************************************************************\
 *                                                                            *
 * Server-Side Skeletons to Invoke Service Operations                         *
 *                                                                            *
\******************************************************************************/

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__store_USCOREfile(struct soap*);

#endif

/* End of soapStub.h */
